### ISSUE TITLE
toRelativeString not supported in swift 3.0?

### ISSUE THREAD

**Issue by pml2571** [malcommac/SwiftDate#259]
I've installed pod 'SwiftDate', :git => 'https://github.com/malcommac/SwiftDate.git', :branch => 'feature/swift-3.0'

But unable to implement toRelativeString() function on both NSDate/DateInRegion

All I'm trying to achieve is to convert a date into "timeago" style

**Comment by iantheparker** [comment]
+1

**Comment by malcommac** [comment]
in SwiftDate 4.0.0 you can use ```colloquialSinceNow()``` or ```colloquial()``` function

**Comment by hackolein** [comment]
When I used this method i always get the following error: "fatal error: 'try!' expression unexpectedly raised an error: SwiftDate.DateError.MissingRsrcBundle: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.46.2/src/swift/stdlib/public/core/ErrorType.swift, line 178"

I tried the example from here http://malcommac.github.io/SwiftDate/formatters.html#colloquial
let dateA = DateInRegion() - 1.months
let (colloquial,relevantTime) = try! dateA.colloquialSinceNow()

The device is an iPhone5 (iOS9) Simulator.
I  used SwiftDate 4.0.1 and Swift3. Any idea what's the problem is?

**Comment by iantheparker** [comment]
I'm getting the same error as @hackolein with this code.

```
let date = try! eventDateString.date(format: .iso8601(options: .withInternetDateTime))
let (colloquial,_) = try! date.colloquialSinceNow()
```

But it is working for me on a generically created Date object.

```
let dateFormatter = DateFormatter()
dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
let sinceDate =  dateFormatter.date(from: published_at)
let (colloquial,_) = try! sinceDate.colloquialSinceNow()
```

**Comment by malcommac** [comment]
Check out with 4.0.2. It should be solved now.

**Comment by iantheparker** [comment]
@malcommac  I'm still getting the same error, but it's breaking on a generic Date init as well.

It works fine in my iPhone 7 simulator, but crashes on my iphone 6 (iOS10) and on my 6/6s simulators running 9.3. Not sure if that helps at all.

**Comment by hackolein** [comment]
@malcommac  I'm still getting the same error. I solved the problem, by adding a new translation for my language. Maybe it makes sense, to have a fallback, if the language not exists.

**Comment by malcommac** [comment]
You are absolutly right. I've scheduled it for the upcoming 4.0.3 release. See #271

**Comment by malcommac** [comment]
Ready :)
