### ISSUE TITLE
Bad timezone with .net date before 1970

### ISSUE THREAD

**Issue by jojo91** [malcommac/SwiftDate#427]
Hi, I have found an issue with the .net format.
It appears that when a date is before 1970, the timezone saved is not good.

Here is my code and my test.
```
let myDotNetDate = "My Date"
if let date = try? myDotNetDate.date(format: .dotNET), let finalDate = date.absoluteDate {
	print(myDotNetDate)
	print(finalDate.string(format: .dotNET))
}
```
Here is the return of my test :

```
Date from 1927
/Date(-1330563600000+0100)/
/Date(-1330563600000+0000)/
```
```
Date from 1990
/Date(641858400000+0200)/
/Date(641858400000+0200)/
```

The result is supposed to be the same in 1927 like in 1990 but it's not.

**Comment by malcommac** [comment]
Fixed for 4.1.2. Details in commit alongside tests.
Thank you!

**Comment by jojo91** [comment]
Hi, I've tried your fix and it seems that the issue is still here.
My test :
```
