### ISSUE TITLE
'range(at:)' has been renamed?

### ISSUE THREAD

**Issue by lynnx4869** [malcommac/SwiftDate#493]
DOTNETDateTimeFormatter.swift:47:85: 'range(at:)' has been renamed to 'rangeAt(_:)'
and have some same problems, how to fix?

**Comment by malcommac** [comment]
What version are you using? Are you compiling with Swift 4?

**Comment by nguyentrai2011** [comment]
@malcommac i'm using version 4.4.1 and have the same issue

**Comment by readefries** [comment]
The [PR-487](https://github.com/malcommac/SwiftDate/pull/487) to fix this, is added to the 4.4.2 release. Hopefully @malcommac will release it soon to Cocoapods.

**Comment by malcommac** [comment]
Fixed in https://github.com/malcommac/SwiftDate/commit/e993a1b13ea9c9588e29c79b7543c310be88da63

**Comment by readefries** [comment]
Hey @malcommac the merging around, reverted this change and now it's still broken :/

**Comment by kohdesmond** [comment]
"Installing SwiftDate 4.4.2 (was 4.1.10)"
Still have the `"Pods/SwiftDate/Sources/SwiftDate/DOTNETDateTimeFormatter.swift:47:85: 'range(at:)' has been renamed to 'rangeAt(_:)'"` error
