### ISSUE TITLE
range(at:) has been renamed to rangeAt(_:)

### ISSUE THREAD

**Issue by archerLj** [malcommac/SwiftDate#523]
SwiftDate version:  4.5.1
Xcode version: Version 9.2 (9C40b)

I got the error:
```
 'range(at:)' has been renamed to 'rangeAt(_:)'
 'range(at:)' was introduced in Swift 4
```

**Comment by archerLj** [comment]
Is this a bug???

The same problem was asked at [#493](https://github.com/malcommac/SwiftDate/issues/493), and some said it was fixed at version 4.42, but i still got this error.

Someone please help me.

**Comment by astrochili** [comment]
It seems like a syntax bug and reproduces on swift 4 only. There is pull request - https://github.com/malcommac/SwiftDate/pull/520
I use fork with a fix for now (https://github.com/jonicong/SwiftDate), it works fine.

**Comment by ricardosou** [comment]
Can anyone please provide a bit more clarity to this issue?
My project is using swift 4 and I'm still seeing this when I update to the latest SwiftDate.

**Comment by bryanbartow** [comment]
6+ months and this still hasn't been fixed, @malcommac?
