### ISSUE TITLE
Fixed Decodable support for DateInRegion, compactMap in Swift 4.0

### ISSUE THREAD

**Issue by JustClear** [malcommac/SwiftDate#582]
When I import SwiftDate.
I got this error:

![image](https://user-images.githubusercontent.com/7371867/44520758-6ff70400-a703-11e8-9a95-503101264fdf.png)

**Comment by malcommac** [comment]
Fixed for 5.0.8.
Thank you for your support.

**Comment by JustClear** [comment]
Thanks Too. 🙏

**Comment by devansh1110** [comment]
Hi, 

This is still not working. Running Version 5.0, as stated in the installation docs. 

Thanks,
