### ISSUE TITLE
toISODate(region:) ignores explicitly passed Region

### ISSUE THREAD

**Issue by ifabijanovic** [malcommac/SwiftDate#670]
Parsing a date string that contains only a date component using the ISO formatter with region specified ignores the passed in region and returns in GMT.

Local region is - gregorian, America/New_York, en_US
`2019-05-06.toISODate(region: .local)` returns DateInRange in GMT timezone
`2019-05-06.toDate(nil, region: .local)` returns DateInRegion in correct timezone

Is this intended?

**Comment by malcommac** [comment]
No, it was a bug.
Thanks, it was fixed in 6.0.3.

**Comment by adrianodiasx93** [comment]
@malcommac is there any chance this bug is still happening? Even though I am passing the region, region is nil when reaching the method.

`Using SwiftDate (6.1.0)`
![Screen Shot 2019-12-21 at 11 14 16](https://user-images.githubusercontent.com/5974969/71309138-298ee380-23e3-11ea-80c3-416d9fd63d28.png)
![Screen Shot 2019-12-21 at 11 14 37](https://user-images.githubusercontent.com/5974969/71309139-298ee380-23e3-11ea-8bf2-4539d3b64d7d.png)

I even tried removing derivated data, cache, all my pods and reinstalling them again, but this behaviour keeps happening. Any idea what might be happening?
